plugins/ginv2/intercepter.go
plugins/http/go.mod
plugins/http/go.sum
plugins/http/instrument.go
plugins/http/intercepter.go
tools/go-agent/go.mod
tools/go-agent/instrument/plugins/enhance_method.go
tools/go-agent/instrument/plugins/instrument.go
tools/go-agent/instrument/plugins/rewrite/context.go
tools/go-agent/instrument/plugins/rewrite/func.go
tools/go-agent/instrument/plugins/templates/method_inserts.tmpl
tools/go-agent/instrument/plugins/templates/method_intercept_after.tmpl
tools/go-agent/instrument/plugins/templates/method_intercept_before.tmpl
tools/go-agent/tools/enhancement.go
tools/go-agent/tools/types.go

Support native HTTP-client plugin, and fix some template bugs when intercepted methods have results.
Here are screenshots when sending traffic to services(consumer and provider):

Support native http-client plugin

---

docs/en/agent/performance-tests.md

I am adding this by following @basvanbeek suggestion.

Add explanation for extra payload

---

.github/workflows/plugin-tests.yaml
docs/en/agent/support-plugins.md
docs/en/development-and-contribution/development-guide.md
go.work
plugins/core/operator/intercepter.go
plugins/core/operator/intercepter_test_base.go
plugins/core/operator/invocation.go
plugins/http/client_intercepter.go
plugins/http/client_intercepter_test.go
plugins/http/instrument.go
plugins/http/server_intercepter.go
plugins/http/server_intercepter_test.go
test/plugins/run.sh
test/plugins/runner-helper/templates/scenarios.tpl
test/plugins/scenarios/http/bin/startup.sh
test/plugins/scenarios/http/config/excepted.yml
test/plugins/scenarios/http/go.mod
test/plugins/scenarios/http/main.go
test/plugins/scenarios/http/plugin.yml
tools/go-agent/instrument/plugins/enhance_method.go
tools/go-agent/instrument/plugins/instrument.go
tools/go-agent/instrument/plugins/rewrite/context.go
tools/go-agent/instrument/plugins/rewrite/func.go
tools/go-agent/instrument/plugins/templates/method_inserts.tmpl
tools/go-agent/instrument/plugins/templates/method_intercept_after.tmpl
tools/go-agent/instrument/plugins/templates/method_intercept_before.tmpl
tools/go-agent/tools/copy.go
tools/go-agent/tools/dst.go

1. Support monitor HTTP server in native HTTP plugin
2. Add HTTP plugin test
3. Update `Invocation` as an interface for plugin development, add the `ChangeArg` method to change the real method argument

Add native http server plugin and tests

---

.github/workflows/plugin-tests.yaml
docs/en/agent/support-plugins.md
docs/en/development-and-contribution/development-guide.md
go.work
plugins/core/instrument/declare.go
plugins/core/span_default.go
plugins/core/span_tracing.go
plugins/core/tracing.go
plugins/go-restfulv3/add_filter.go
plugins/go-restfulv3/filter.go
plugins/go-restfulv3/filter_test.go
plugins/go-restfulv3/go.mod
plugins/go-restfulv3/go.sum
plugins/go-restfulv3/instrument.go
test/plugins/scenarios/go-restfulv3/bin/startup.sh
test/plugins/scenarios/go-restfulv3/config/excepted.yml
test/plugins/scenarios/go-restfulv3/go.mod
test/plugins/scenarios/go-restfulv3/go.sum
test/plugins/scenarios/go-restfulv3/main.go
test/plugins/scenarios/go-restfulv3/plugin.yml
tools/go-agent/instrument/plugins/enhance_instance.go
tools/go-agent/instrument/plugins/enhance_method.go
tools/go-agent/instrument/plugins/instrument.go
tools/go-agent/instrument/plugins/rewrite/context.go
tools/go-agent/tools/dst.go

1. Support go-restful framework with v3 version
2. Support overwide operation names avoid to create multiple entry span
3. Support overwrite span tag

Support go-restful framework with v3 version

---

CHANGES.md
tools/go-agent/instrument/plugins/rewrite/context.go
tools/go-agent/instrument/plugins/rewrite/func.go

Following https://github.com/apache/skywalking-go/pull/55#issuecomment-1579802069, enhance the plugin rewrite ability:
* `condition in the if` statement
* `type switch` statement.

Enhance the plugin rewrite ability

---

tools/go-agent/tools/vendor_test.go

Following https://github.com/apache/skywalking-go/pull/78#discussion_r1268535961

Add tests for `UnVendor`

---

docs/en/advanced-features/manual-apis/toolkit-trace.md

Update documentation for advanced feature tracing

fix: Update toolkit-trace.md

---

docs/en/advanced-features/manual-apis/toolkit-trace.md
plugins/trace-activation/instrument.go
plugins/trace-activation/set_component_interceptor.go
test/plugins/scenarios/trace-activation/config/excepted.yml
test/plugins/scenarios/trace-activation/test_service.go
toolkit/trace/api.go

- Add SetComponent() to toolkit-trace
- Add example of ExtractorRef and InjectorRef to document of toolkiit-trace
- Update the document of toolkiit-trace

feat: Add SetComponent() to toolkit-trace

---

plugins/go-redisv9/op_type.go

fix: add redis rw operation

---

.gitignore
CHANGES.md
tools/go-agent/tools/testdata/special-modules.txt
tools/go-agent/tools/vendor.go
tools/go-agent/tools/vendor_test.go

fix [#11718](https://github.com/apache/skywalking/issues/11718)

fix special case for ParseVendorModule

---

plugins/core/reporter/grpc/grpc.go

fix [#11832](https://github.com/apache/skywalking/issues/11832)

Fix stack overflow as endless logs triggered

---

CHANGES.md
docs/en/agent/plugin-configurations.md
plugins/core/tools/strconv.go
plugins/core/tracer_tools.go
plugins/core/tracing/span.go
plugins/gin/config.go
plugins/gin/intercepter.go
plugins/gin/intercepter_test.go
test/plugins/scenarios/gin/bin/startup.sh
test/plugins/scenarios/gin/config/excepted.yml
test/plugins/scenarios/gin/main.go
tools/go-agent/config/agent.default.yaml
tools/go-agent/instrument/plugins/enhance_config.go

Supporting http headers collection for Gin

Supporting http headers collection for Gin

---

tools/go-agent/cmd/helper.go

Use a more standardized command usage format to enhance output.

fix: Enhance usage template

---

CHANGES.md
plugins/mux/instrument.go
plugins/mux/serve_interceptor.go
test/plugins/scenarios/mux/config/excepted.yml
test/plugins/scenarios/mux/go.mod
test/plugins/scenarios/mux/go.sum
test/plugins/scenarios/mux/main.go

Work with weboskcet library(e.g https://github.com/gorilla/websocket), `writerWrapper` should implement `http.Hijacker`

feat: impl http.Hijacker

---

CHANGES.md
plugins/gorm/entry/callback.go
plugins/gorm/entry/config.go
plugins/gorm/entry/interceptor_test.go
test/plugins/scenarios/gorm/bin/startup.sh
test/plugins/scenarios/gorm/config/excepted.yml
tools/go-agent/config/agent.default.yaml

feat: add tracing.TagDBStatement and tracing.TagDBSqlParameters for gorm

feat: add tracing.TagDBStatement and tracing.TagDBSqlParameters for gorm

---

CHANGES.md
test/plugins/scenarios/gin/plugin.yml
test/plugins/scenarios/http/plugin.yml
test/plugins/scenarios/trace-activation/plugin.yml
tools/go-agent/instrument/api/flags.go
tools/go-agent/instrument/runtime/instrument.go

Resolved https://github.com/apache/skywalking/issues/12542

Support enhancement with go 1.23

---

CHANGES.md
plugins/core/tracing.go

Fix https://github.com/apache/skywalking/issues/12345

Fix got `span type is wrong` error when creating exit span with trace sampling

---

.licenserc.yaml

Fix another issue found in the voting process.

Add generated VERSION file into license ignoring list.

---

docs/en/development-and-contribution/how-to-release.md

Remove wrong link in vote mail from how-to-release doc

---

CHANGES.md
plugins/go-redisv9/hook.go

Fix https://github.com/apache/skywalking/discussions/12593

Fix redis plugin cannot work in cluster mode

---

plugins/core/logreport.go

fix interface nil exception

---

.github/workflows/windows-plugin-test.yaml

feat(ci): add GitHub Actions plugin test workflow for Windows
It's just a mock file. I'm testing locally and expect to commit over the next few nights.

feat(ci): add GitHub Actions plugin test workflow for Windows

---

docs/en/concepts-and-designs/project-structure.md

According to the structure of the current project, I thick `reporter` should under the `plugin/core` section, so maybe docs need to be updated.

chore: update docs
