apache/skywalking-go

- test/plugins/runner-helper/templates/scenarios.tpl
When running the run.sh script under skywalking-go/test/plugins, the container name service defined in scenarios.tpl appears_ container_ name，validator_ container_ name.The connection symbol in name is "_", while the container's connection symbol is "-" after docker-compose.yml is started, which causes the scenario. sh runtime to be unable to obtain the corresponding information, resulting in run.sh failure
Before change
After change
> Fix container name inconsistency in file scenarios.tpl

- plugins/core/context.go
- plugins/core/id.go
- plugins/core/id_test.go
- plugins/core/span_tracing.go
- plugins/core/tool.go
- plugins/core/tracing.go
- tools/go-agent/instrument/agentcore/instrument.go
- tools/go-agent/instrument/consts/operator.go
- tools/go-agent/instrument/runtime/instrument.go
Following https://github.com/apache/skywalking/issues/10849, I have refactored the ID generator. 
ID generate format(same with java): `{instanceID}.{goid}.{timestamp}{sequence}`. We bind the `IDContext` to each goroutine(using TLS) to reduce the global locker.
Here are simple batch marks for comparison with UUID：
```
goos: darwin
goarch: amd64
pkg: github.com/apache/skywalking-go/plugins/core
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkGenerateID
BenchmarkGenerateID-16             	  956929	      1168 ns/op
BenchmarkGenerateIDParallels
BenchmarkGenerateIDParallels-16    	 4309476	       323.3 ns/op
BenchmarkUUID
BenchmarkUUID-16                   	 1000000	      1008 ns/op
BenchmarkUUIDParallels
BenchmarkUUIDParallels-16          	  856684	      1341 ns/op
PASS
```
I will do …
> Refactor the global ID generator

- CHANGES.md
- tools/go-agent/instrument/plugins/instrument.go
- tools/go-agent/instrument/plugins/instrument_test.go
When running with `-toolexec`, go module path would be accessed and used as input argument:
```
time="2023-06-15T16:55:11+08:00" level=info msg="executing instrument with args: [-debug /home/jiekun/repo/github.com/skywalking-go /home/jiekun/go/go1.18.10/pkg/tool/linux_amd64/compile -o /tmp/go-build3202628928/b271/_pkg_.a -trimpath /tmp/go-build3202628928/b271=> -p github.com/redis/go-redis/v9 -lang=go1.18 -complete -buildid HdoJ2T0oKPptxg-YD8IU/HdoJ2T0oKPptxg-YD8IU -goversion go1.18.10 -N -l -c=4 -nolocalimports -importcfg /tmp/go-build3202628928/b271/importcfg -pack /home/jiekun/go/pkg/mod/github.com/redis/go-redis/v9@v9.0.5/cluster.go /home/jiekun/go/pkg/mod/github.com/redis/go-redis/v9@v9.0.5/cluster_commands.go /home/jiekun/go/pkg/mod/github.com/redis/go-redis/v9@v9.0.5/command.go …
```
> bug: Fix plugin version matcher to support capital letters in module paths and versions

- .github/workflows/plugin-tests.yaml
- .github/workflows/skywalking-go.yaml
`Build Plugin Test On macos` was failed because `error starting vm: error at 'starting': exit status 1`
Build on `macos-latest` --> Build on  `macos-13`
> fix: CI test build on macos failed

- docs/en/agent/performance-tests.md
remove the last character(") of the last part in Sw8(AddressUsedAtClient) which cause base64 decode error.
error info:
```
skywalking-go 2023/09/11 11:04:29 execute interceptor before invoke error, instrument name: gin, interceptor name: HTTPInterceptor, function ID: github_com_gin_gonic_gin_EnginehandleHTTPRequest, error: network address parse error: illegal base64 data at input byte 24
```
source code:
```go
s.AddressUsedAtClient, err = decodeBase64(hh[7])
if err != nil {
return errors.Wrap(err, "network address parse error")
}
```
> fix header Sw8 in request.txt

- docs/en/setup/docker.md
See also the test output:
```shell
[root@ailink-master1 ~]# docker pull apache/skywalking-go-agent:0.1.0-go1.20
Error response from daemon: pull access denied for apache/skywalking-go-agent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[root@ailink-master1 ~]# docker pull apache/skywalking-go:0.2.0-go1.20
0.2.0-go1.20: Pulling from apache/skywalking-go
```
> doc: correct the image name to be apache/skywalking-go

- tools/go-agent/Makefile
I wan't to build skywalking-go agent on arm64 platform, but I found that Makefile defines ARCH=amd64 with dead code, so I update the Makefile, that I can compile arm64 platform with:
```
make build ARCH=arm64
```
> feat: update Makefile to support build arm64 platform

- docs/menu.yml
Fix problem：https://github.com/apache/skywalking-go/pull/104#issuecomment-1770349895
- Remove the suffix from the path of toolkit-trace documentation
> Fix url about toolkit-trace documentation

- CHANGES.md
- docs/en/advanced-features/manual-apis/toolkit-trace.md
- plugins/trace-activation/async_finish_intercepter.go
- plugins/trace-activation/async_log_intercepter.go
- plugins/trace-activation/async_tag_intercepter.go
- plugins/trace-activation/create_entryspan_intercepter.go
- plugins/trace-activation/create_exitspan_intercepter.go
- plugins/trace-activation/create_localspan_intercepter.go
- plugins/trace-activation/instrument.go
- test/plugins/scenarios/trace-activation/config/excepted.yml
- test/plugins/scenarios/trace-activation/main.go
- test/plugins/scenarios/trace-activation/test_service.go
- toolkit/trace/api.go
- toolkit/trace/span.go
In the process of writing my blog, I found that Async API in manual APIs are not available to users because users cannot pass Span into other goroutines. I accidentally overlooked this before.
Then I referred to JAVA and found that it provides users with a `spanRef` to use async api. (I've defined this `spanRef`, but it's currently no use)
So I changed the async api.
- fix Async API in manual APIs
- Supplement cross goroutine async test
> fix: users can not use async api in toolkit-trace

- CHANGES.md
- docs/en/agent/plugin-configurations.md
- plugins/go-redisv9/config.go
- plugins/go-redisv9/hook.go
- test/plugins/scenarios/go-redisv9/bin/startup.sh
- tools/go-agent/config/agent.default.yaml
- tools/go-agent/instrument/plugins/enhance_config.go
limit the bytes of redis args.
> fix: limit the bytes of redis args

- CHANGES.md
- plugins/core/reporter/grpc/grpc_opts_enhance.go
for the setting SW_AGENT_REPORTER_GRPC_MAX_SEND_QUEUE in the https://github.com/apache/skywalking-go/blob/99c2c38ff78507db17aa14839047219a2a6c99b8/tools/go-agent/config/agent.default.yaml
found out that its not working on metricsSendCh & logSendCh chans
> bugfix:forget to set metrics & log ch as well

- CHANGES.md
- plugins/core/span_noop.go
- plugins/core/span_tracing.go
- plugins/core/tracing.go
- plugins/core/tracing_test.go
Following https://github.com/apache/skywalking/discussions/11748, there is a tracing context bug when the trace is sampled
> Fix wrong tracing context when trace have been sampled

- CHANGES.md
- docs/en/agent/tracing-metrics-logging.md
- plugins/core/tracer.go
- plugins/core/tracing.go
- tools/go-agent/config/agent.default.yaml
- tools/go-agent/config/loader.go
- tools/go-agent/instrument/agentcore/instrument.go
add support ignore suffix
Provide users with the ability to ignore the span for the operationName dimension.
In the actual usage environment, there are a batch of requests such as /xx.jpg. We can reduce the signal-to-noise ratio of the collection to better analyze the trace.
I added `agent.ignore_suffix` in the default configuration file, which will add a layer of judgment when creating Entry, Local and Exit spans.
There is no test code added for the time being. Since I am considering the operationName dimension, I would like to discuss the topic [11807](https://github.com/apache/skywalking/discussions/11807) with community members~
> Add support ignore suffix

- CHANGES.md
- plugins/gin/intercepter.go
- plugins/gin/structures.go
using the index of `[]HandlerFunc`, determine if the current is the first HandlerFunc, and then handle the enhancement
[#11852](https://github.com/apache/skywalking/issues/11852)
> fix lost trace when multi middleware handlerFunc

- Makefile
Currently SkyWalking Go provided image as the base image, which currently supports the following Go versions: 1.16, 1.17, 1.18, 1.19, 1.20
but we need to support 1.21 and even 1.22
> feature: add golang 1.21, 1.22 compatibility for docker image

- CHANGES.md
- docs/en/agent/tracing-metrics-logging.md
- plugins/core/tracer.go
- plugins/core/tracer_ignore.go
- plugins/core/tracer_ignore_test.go
- plugins/core/tracing.go
- tools/go-agent/config/agent.default.yaml
- tools/go-agent/config/loader.go
- tools/go-agent/instrument/agentcore/instrument.go
If the operation name of the first span is matching, this segment should be ignored.(multiple split by ","), matching rules follow Ant Path match style, like /path/*, /path/**, /path/?.
> Add support trace ignore

- CHANGES.md
- Makefile
In the current PR, the makefile has been enhanced, mainly including the following two enhancements:
+ Add `$(LOG_TARGET)` to support printing make execution target information highlighting
+ Add `make help` command to help users more conveniently understand the TARGET allowed to be executed in make
like below:
```shell
[root@shy code]# make help
Usage:
make <target>
General
help             Display this help.
Golang
test             Run E2E scenario tests
lint             Run golangci-lint linter
check            Run consistency checks
build            Build skywalking-go agent binary
release          Build skywalking-go agent release
Docker
docker           Build docker images for skywalking-go agent and Push docker images to registry
```
> chore: enhance makefile

- .github/workflows/plugin-tests.yaml
- CHANGES.md
- docs/en/agent/support-plugins.md
- go.work
- plugins/core/tracer_ignore.go
- plugins/go-elasticsearchv8/go.mod
- plugins/go-elasticsearchv8/go.sum
- plugins/go-elasticsearchv8/instrument.go
- plugins/go-elasticsearchv8/intercepter.go
- plugins/http/client_intercepter.go
- test/plugins/scenarios/amqp/config/excepted.yml
- test/plugins/scenarios/amqp/main.go
- test/plugins/scenarios/go-elasticsearchv8/bin/startup.sh
- test/plugins/scenarios/go-elasticsearchv8/config/elasticsearch.yml
- test/plugins/scenarios/go-elasticsearchv8/config/excepted.yml
- test/plugins/scenarios/go-elasticsearchv8/go.mod
- test/plugins/scenarios/go-elasticsearchv8/go.sum
- test/plugins/scenarios/go-elasticsearchv8/main.go
- test/plugins/scenarios/go-elasticsearchv8/plugin.yml
- test/plugins/scenarios/grpc/config/excepted.yml
- test/plugins/scenarios/rocketmq/config/excepted.yml
- test/plugins/scenarios/trace-activation/config/excepted.yml
- tools/go-agent/instrument/plugins/register.go
- tools/go-agent/instrument/plugins/templates/method_intercept_after.tmpl
[go-elasticsearch](https://github.com/elastic/go-elasticsearch) is the official Go client for Elasticsearch.
> Add support for go-elasticsearch

- CHANGES.md
- plugins/gin/intercepter.go
- plugins/gin/intercepter_test.go
- test/plugins/scenarios/gin/config/excepted.yml
- test/plugins/scenarios/gin/main.go
fix: when not route is found, the gin operation name is "http.Method:", example: "GET:".
> fix: when not route is found, the gin operation name is "http.Method:", example: "GET:".

- toolkit/log/api.go
- toolkit/metric/api.go
- toolkit/metric/metrics.go
- toolkit/trace/span.go
Current PR is used to design the `toolkit` API, which mainly designs three aspects: trace, metric, log
+ trace: supports attaching events to spans.
+ log: supports manually calling logs
+ metric: supports manually building commonly used metrics
> api: add log,metric,span feat to api

- CHANGES.md
- Makefile
- tools/go-agent/Makefile
- tools/go-agent/cmd/helper.go
When I tried to push the docker image, found the image names always start with git version instant of version, so I fixed it in this PR.
> Fix wrong docker image name and `-version` command

- CHANGES.md
- plugins/core/tracing/api.go
- plugins/trace-activation/instrument.go
- plugins/trace-activation/trace/add_event_intercepter.go
- plugins/trace-activation/trace/async_add_event_intercepter.go
- plugins/trace-activation/trace/consts.go
- test/plugins/scenarios/trace-activation/config/excepted.yml
- test/plugins/scenarios/trace-activation/main.go
- test/plugins/scenarios/trace-activation/test_service.go
- toolkit/trace/api.go
- tools/go-agent/instrument/plugins/rewrite/rewrite.go
What type of PR?
> feat: toolkit span add event api impl
What did you do?
> Completed the implementation of the `AddEvent` API in `toolkit/span`. Support attaching Event to Span in manual mode.
> feat: toolkit span add event impl

- .github/workflows/plugin-tests.yaml
- .github/workflows/skywalking-go.yaml
After the recent actions CI (such as [CI-1](https://github.com/apache/skywalking-go/actions/runs/10920895152/job/30312587712)) find that v2 does not work, so upgrade to v4 to solve this problem.
> Bump up actions/upload-artifact and actions/download-artifact to v4

- CHANGES.md
- docs/en/advanced-features/manual-apis/toolkit-log.md
- docs/en/advanced-features/manual-apis/toolkit-metric.md
- docs/en/advanced-features/manual-apis/toolkit-trace.md
- docs/menu.yml
This PR mainly supplements the documentation for new toolkit features.
Mainly focuses on the following three points:
+ trace: Supplemented `AddEvent` documentation
+ logging: Added `toolkit/logging` usage documentation
+ metric: Added `toolkit/metric` usage documentation
> docs: add toolkit docs

- CHANGES.md
- test/plugins/Makefile
- tools/go-agent/Makefile
When the VERSION of the root directory is not empty, executing make build in test/plugins will cannot find the binary file.
> Fix cannot find file when exec build in test/plugins

- CHANGES.md
- plugins/core/span_default.go
- plugins/core/span_noop.go
- plugins/core/span_tracing.go
- plugins/core/tracing/api.go
- plugins/core/tracing/bridge.go
- plugins/core/tracing/span.go
- plugins/gin/intercepter.go
- plugins/http/client_intercepter.go
- plugins/http/client_intercepter_test.go
- plugins/http/server_intercepter.go
- plugins/http/server_intercepter_test.go
- plugins/toolkit-activation/instrument.go
- plugins/toolkit-activation/trace/error_intercepter.go
- test/plugins/scenarios/gin/config/excepted.yml
- test/plugins/scenarios/http/config/excepted.yml
- test/plugins/scenarios/http/main.go
- toolkit/trace/api.go
1、add logic when http status code >= 400, set span isError is true by span.Error method
2、add new method trace.Error for user set san isError to true by self
> Support span in error status when http code >= 400, and add trace#Error in toolkit API

- .github/workflows/plugin-tests.yaml
- CHANGES.md
- go.work
- test/plugins/scenarios/cross-goroutine/bin/startup.sh
- test/plugins/scenarios/cross-goroutine/config/excepted.yml
- test/plugins/scenarios/cross-goroutine/go.mod
- test/plugins/scenarios/cross-goroutine/main.go
- test/plugins/scenarios/cross-goroutine/plugin.yml
- test/plugins/scenarios/irisv12/plugin.yml
- tools/go-agent/instrument/api/flags.go
- tools/go-agent/instrument/runtime/instrument.go
Fixes #13188
**Problem:**
The runtime instrumentation logic in `tools/go-agent/instrument/runtime/instrument.go` incorrectly checked for a hardcoded number of parameters (3) for the internal `runtime.newproc1` function. This check failed for Go versions 1.23 and later, where the relevant function signature expects 2 parameters for the instrumentation purpose. Consequently, the agent skipped the injection of the necessary code for automatic context propagation when new goroutines were created using `newproc1`, breaking automatic tracing in Go 1.23+ environments.
**Solution:**
This patch addresses the issue by implementing dynamic parameter count checking based on the Go version specified during compilation via the `-lang` flag:
1.  **Introduced Robust Version Checking:** Added a new method …
> Fix: Correctly instrument newproc1 for Go 1.23+ parameter counts (#13188)

- plugins/core/reporter/discard_reporter.go
- plugins/core/reporter/discard_reporter_test.go
- plugins/core/tracer.go
This PR replaces the custom `emptyReporter` implementation in `plugins/core/tracer.go` with the existing `reporter.NewDiscardReporter()` to reduce code duplication and improve maintainability.
- Replace `&emptyReporter{}` with `reporter.NewDiscardReporter()` in the `newTracer()` method
- Remove the redundant `emptyReporter` struct and its method implementations
The `emptyReporter` and `DiscardReporter` have identical functionality - they both implement the Reporter interface but don't perform any actual operations. Using the existing `DiscardReporter` implementation reduces code duplication and follows the DRY principle.
> Refactor: Replace emptyReporter with DiscardReporter

- plugins/core/context.go
Since the Go agent adds a new goroutine to the tracing snapshot during `new_proc1`, it uses a defer statement to perform the unlock operation. However, because `new_proc1` returns a new goroutine, it differs from the one executing the defer statement, which leads to a fatal error.
> Remove defer unlock when goroutine change
